apply plugin: 'java-library'
evaluationDependsOn(':core-source-api')
java { sourceCompatibility = JavaVersion.VERSION_17; targetCompatibility = JavaVersion.VERSION_17 }
def sourceApiJar = project(':core-source-api').tasks.named('jar').flatMap { it.archiveFile }
dependencies { api files(sourceApiJar) }
tasks.withType(JavaCompile).configureEach { dependsOn ':core-source-api:jar' }
